name: Check

on:
  pull_request:

jobs:
  sbt:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        command:
        - compile
        - test
        - scalafmtCheckAll
        - scalastyle
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - run: sbt ${{ matrix.command }}
      working-directory: transformer
